### ISSUE TITLE
Security flaw on exec in ping

### ISSUE THREAD

**Issue by Nephos** [alpha14/hal42#1]
The ping command has a security flaw

``` javascript
    exec('ping -c 1 -W 2 ' + encodeURI(message.substring(6)) ...
```

the message may contain malicious cmds, like "8.8.8.8&&ls&&ls" etc.

There is no way to add arguments to the command via a space, and we cannot dos with the yes command because of the timeout on the child process.

**Comment by Nephos** [comment]
fucking use a regexp

**Comment by Nephos** [comment]
is there a native function to ping in nodejs ?

**Comment by Emeraude** [comment]
On peut assigner qu'une seule personne à un ticket sur cette merde ?

**Comment by Nephos** [comment]
en fait c'est le principe d'assigner une tâche. Tu peux faire en sorte que plusieurs personnes la suive (@) mais il n'y a qu'un seul responsable. Comme au zappy B-)

**Comment by Nephos** [comment]
@alpha14 code au lieu de te dorer les fesses au soleil.

**Comment by Emeraude** [comment]
I removed the ping feature from the master branch, it's only in **instable-ping** branch now.

**Comment by Nephos** [comment]
\o

**Comment by Nephos** [comment]
\o/
